### ISSUE TITLE
how about comparing their MCC?

### ISSUE THREAD

**Issue by UnixJunkie** [PatWalters/comparing_classifiers#1]
If you really compare their classification (not ranking) power.

**Comment by UnixJunkie** [comment]
For example, iterate 50 times with molecules list randomization each time, train on 80%, test on the 20% left out test set.
Then compare the distributions of their MCCs.

**Comment by PatWalters** [comment]
Yes, you can do that.  Need to use a non-parametric method like Wilcoxon.  In this case, I was focused on AUC.  I have a blog post coming shortly that explains.

**Comment by UnixJunkie** [comment]
Ok, keep up with the super interesting chemoinformatics blog!
